// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dravenrjvgjenvhrqbpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyYXZlbnJqdmdqZW52aHJxYnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzIzMDQsImV4cCI6MjA1ODY0ODMwNH0.4GrvMHap1JlFVm1XD9v09EgxkIVWNnKO_4wZVL95cUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);